### PR TITLE
Fix/experience post creation

### LINKED ISSUE #157: Creation of Experience Post has bugs
- It is possible to create an experience post even though you are not from the given municipality of the data set. To reproduce create an experience post on an issue that have another municipality than the user you are testing with.

- ~~It is also possible to overwrite an article by saving the URL and UUID and thereby manually injecting an article again.~~

### PR DESCRIPTION
**Pull request by Letaguator**
Closes #157.

### CODE REVIEW

File: backend/Controllers/MetadataController.cs [hunk 1]
```diff
@@ -105,7 +105,13 @@ public async Task<IActionResult> SetExperience([FromBody] SaveExperiencePostReso
 			}
 			if (!ModelState.IsValid)
 				return BadRequest(ModelState.GetErrorMessages());
-			
+
+
+			if (user.UserType < UserType.Municipality || user.MunicipalityName != metadata.MunicipalityName)
```
Comment (fipa98) [inline backend/Controllers/MetadataController.cs:110]: "!=" instead of "<" ?

Comment (Letaguator) [reply backend/Controllers/MetadataController.cs:110]: It is < to ensure roles with more privileges than municipality still can add an experience post.
